# Generated by Django 3.0.2 on 2020-01-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astring', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MySecondModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bug_app.MyFirstModel')),
            ],
        ),
    ]
